# Generated by Django 4.1.7 on 2023-04-03 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.TextField(max_length=50)),
                ('actors_photo', models.ImageField(null=True, upload_to='actors_ph')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.CharField(choices=[('Drama', 'Drama'), ('Action', 'Action'), ('Crime', 'Crime'), ('Romance', 'Romance'), ('Sci_Fi', 'Sci_Fi'), ('Horror', 'Horror'), ('Adventure', 'Adventure'), ('Anime', 'Anime'), ('Exitement', 'Exitement')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LoginOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('poster', models.ImageField(null=True, upload_to='posters')),
                ('actors', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='msite.actors')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='msite.category')),
            ],
        ),
    ]
