# Generated by Django 4.1.7 on 2023-04-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmovie',
            name='category',
        ),
        migrations.AddField(
            model_name='mainmovie',
            name='category',
            field=models.ManyToManyField(to='msite.category'),
        ),
    ]
