# Generated by Django 4.1.7 on 2023-04-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0002_remove_mainmovie_category_mainmovie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmovie',
            name='movie',
            field=models.FileField(null=True, upload_to='movie'),
        ),
        migrations.AddField(
            model_name='mainmovie',
            name='trailer',
            field=models.FileField(null=True, upload_to='trailer'),
        ),
    ]
