# Generated by Django 4.1.7 on 2023-04-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0003_mainmovie_movie_mainmovie_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmovie',
            name='actors',
        ),
        migrations.AddField(
            model_name='mainmovie',
            name='actors',
            field=models.ManyToManyField(to='msite.actors'),
        ),
    ]
