# Generated by Django 4.1.7 on 2023-04-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0004_remove_mainmovie_actors_mainmovie_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginout',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
