# Generated by Django 4.1.7 on 2023-04-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0005_alter_loginout_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginout',
            name='username',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
