# Generated by Django 4.1.7 on 2023-04-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0006_alter_loginout_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmovie',
            name='about',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
