# Generated by Django 4.1.7 on 2023-04-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0007_mainmovie_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginOut',
        ),
    ]
