# Generated by Django 4.1.7 on 2023-04-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0008_delete_loginout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmovie',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='mainmovie',
            name='category',
            field=models.CharField(choices=[('D', 'Drama'), ('A', 'Action'), ('C', 'Crime'), ('R', 'Romance'), ('S', 'Sci_Fi'), ('H', 'Horror'), ('A', 'Adventure'), ('A', 'Anime'), ('E', 'Exitement')], max_length=2, null=True),
        ),
    ]
