# Generated by Django 4.1.7 on 2023-04-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0010_category_remove_mainmovie_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmovie',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='mainmovie',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
