# Generated by Django 4.1.7 on 2023-04-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0011_remove_mainmovie_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmovie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='msite.actors'),
        ),
    ]
