# Generated by Django 4.1.7 on 2023-04-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0012_alter_mainmovie_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmovie',
            name='actors',
            field=models.ManyToManyField(related_name='actors', to='msite.actors'),
        ),
    ]
