# Generated by Django 4.1.7 on 2023-04-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0014_alter_mainmovie_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmovie',
            name='actors',
            field=models.ManyToManyField(to='msite.actors'),
        ),
    ]
