# Generated by Django 4.1.7 on 2023-04-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0015_alter_mainmovie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmovie',
            name='category2',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Action', 'Action'), ('Crime', 'Crime'), ('Romance', 'Romance'), ('Sci_Fi', 'Sci_Fi'), ('Horror', 'Horror'), ('Adventure', 'Adventure'), ('Anime', 'Anime'), ('Exitement', 'Exitement')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mainmovie',
            name='category',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Action', 'Action'), ('Crime', 'Crime'), ('Romance', 'Romance'), ('Sci_Fi', 'Sci_Fi'), ('Horror', 'Horror'), ('Adventure', 'Adventure'), ('Anime', 'Anime'), ('Exitement', 'Exitement')], max_length=50, null=True),
        ),
    ]
