# Generated by Django 4.1.7 on 2023-04-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0017_alter_mainmovie_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmovie',
            name='actors',
            field=models.ManyToManyField(related_name='acto', related_query_name='acto', to='msite.actors'),
        ),
    ]
