# Generated by Django 4.1.7 on 2023-04-25 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0019_alter_mainmovie_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmovie',
            name='actors',
            field=models.ManyToManyField(to='msite.actors'),
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msite.actors')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msite.mainmovie')),
            ],
        ),
    ]
