# Generated by Django 4.1.7 on 2023-04-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0020_alter_mainmovie_actors_movieactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmovie',
            name='actors',
            field=models.ManyToManyField(related_name='actors', to='msite.actors'),
        ),
    ]
