# Generated by Django 4.1.7 on 2023-04-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0021_alter_mainmovie_actors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieActor',
        ),
    ]
