# Generated by Django 4.1.7 on 2023-05-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0022_delete_movieactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmovie',
            name='movie',
            field=models.FileField(blank=True, null=True, upload_to='movie'),
        ),
        migrations.AlterField(
            model_name='mainmovie',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='trailer'),
        ),
    ]
