# Generated by Django 4.1.7 on 2023-06-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0024_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.CharField(choices=[('Drama', 'Drama'), ('Action', 'Action'), ('Crime', 'Crime'), ('Romance', 'Romance'), ('Sci_Fi', 'Sci_Fi'), ('Horror', 'Horror'), ('Adventure', 'Adventure'), ('Anime', 'Anime'), ('Exitement', 'Exitement')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='mainmovie',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='mainmovie',
            name='category',
        ),
        migrations.AddField(
            model_name='mainmovie',
            name='category',
            field=models.ManyToManyField(related_name='category', to='msite.category'),
        ),
    ]
