# Generated by Django 4.1.7 on 2023-06-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0025_category_remove_mainmovie_category2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate',
            field=models.CharField(max_length=50),
        ),
    ]
