# Generated by Django 4.1.7 on 2023-07-13 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0026_alter_category_cate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_name', models.CharField(blank=True, max_length=100, null=True)),
                ('episode', models.FileField(blank=True, null=True, upload_to='episodes')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.IntegerField(blank=True, null=True)),
                ('episodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msite.episode')),
            ],
        ),
        migrations.CreateModel(
            name='TvShows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('poster', models.ImageField(null=True, upload_to='posters')),
                ('actors', models.ManyToManyField(related_name='TVactors', to='msite.actors')),
                ('category', models.ManyToManyField(related_name='TVcategory', to='msite.category')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msite.part')),
            ],
        ),
    ]
