# Generated by Django 4.1.7 on 2023-07-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0027_episode_part_tvshows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode',
            field=models.FileField(null=True, upload_to='episodes'),
        ),
        migrations.RemoveField(
            model_name='part',
            name='episodes',
        ),
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='episodes',
            field=models.ManyToManyField(related_name='epi', to='msite.episode'),
        ),
    ]
