# Generated by Django 4.1.7 on 2023-07-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0028_alter_episode_episode_remove_part_episodes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshows',
            name='season',
        ),
        migrations.AddField(
            model_name='tvshows',
            name='season',
            field=models.ManyToManyField(related_name='part', to='msite.part'),
        ),
    ]
