# Generated by Django 4.1.7 on 2023-07-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0029_remove_tvshows_season_tvshows_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshows',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
