# Generated by Django 4.1.7 on 2023-07-15 22:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msite', '0031_myfavo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyFavo',
            new_name='MyList',
        ),
    ]
