# Generated by Django 4.1.7 on 2023-07-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0032_rename_myfavo_mylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='def.png', upload_to='profile_pics'),
        ),
    ]
