# Generated by Django 4.1.7 on 2023-07-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0033_alter_userprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='part_number',
            new_name='part_name',
        ),
    ]
