# Generated by Django 4.1.7 on 2023-07-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0034_rename_part_number_part_part_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='poster',
            field=models.ImageField(null=True, upload_to='season_ph'),
        ),
    ]
