# Generated by Django 4.1.7 on 2023-07-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0036_myrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_poster',
            field=models.ImageField(null=True, upload_to='episode_ph'),
        ),
    ]
