# Generated by Django 4.1.7 on 2023-07-19 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0037_episode_episode_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episode_poster',
        ),
    ]
