# Generated by Django 4.1.7 on 2023-07-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0038_remove_episode_episode_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_poster',
            field=models.ImageField(null=True, upload_to='episode_ph'),
        ),
    ]
