# Generated by Django 4.1.7 on 2023-07-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0039_episode_episode_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRecom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msite.mainmovie')),
            ],
        ),
    ]
