# Generated by Django 4.1.7 on 2023-07-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0040_siterecom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siterecom',
            name='movie',
        ),
        migrations.AddField(
            model_name='siterecom',
            name='movie',
            field=models.ManyToManyField(related_name='MainMovie', to='msite.mainmovie'),
        ),
    ]
