# Generated by Django 4.1.7 on 2023-07-24 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0041_remove_siterecom_movie_siterecom_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siterecom',
            name='movie',
        ),
        migrations.AddField(
            model_name='siterecom',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msite.mainmovie'),
        ),
    ]
