# Generated by Django 4.1.7 on 2023-07-25 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msite', '0042_remove_siterecom_movie_siterecom_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTvList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch', models.BooleanField(default=False)),
                ('tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msite.tvshows')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
