# Generated by Django 4.1.7 on 2023-07-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0043_mytvlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmovie',
            name='poster2',
            field=models.ImageField(blank=True, null=True, upload_to='posters2'),
        ),
    ]
