# Generated by Django 4.1.7 on 2023-08-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0044_mainmovie_poster2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshows',
            name='poster2',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
    ]
