# Generated by Django 4.1.7 on 2023-08-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msite', '0045_tvshows_poster2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actors',
            options={'ordering': ['actor_name']},
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_poster2',
            field=models.ImageField(null=True, upload_to='episode_ph2'),
        ),
    ]
